version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/html:/usr/share/nginx/html

  web:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./web/html:/usr/local/apache2/htdocs